/*
 * Matrix Routing
 *
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.matrixrouting.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.matrixrouting.Model
{
    /// <summary>
    /// ListOfLocations
    /// </summary>
    [DataContract(Name = "ListOfLocations")]
    public partial class ListOfLocations : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListOfLocations" /> class.
        /// </summary>
        /// <param name="locations">The list of locations.The first location is the start and the last is the destination of the route. Additional intermediate locations are possible..</param>
        public ListOfLocations(List<Location> locations = default(List<Location>))
        {
            this.Locations = locations;
        }

        /// <summary>
        /// The list of locations.The first location is the start and the last is the destination of the route. Additional intermediate locations are possible.
        /// </summary>
        /// <value>The list of locations.The first location is the start and the last is the destination of the route. Additional intermediate locations are possible.</value>
        [DataMember(Name = "locations", EmitDefaultValue = false)]
        public List<Location> Locations { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListOfLocations {\n");
            sb.Append("  Locations: ").Append(Locations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
