/*
 * Matrix Routing
 *
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.matrixrouting.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.matrixrouting.Model
{
    /// <summary>
    /// Defines the format for the distances, travel times, toll costs, directDistance flags and violation flags in the response. Note that the encoded format should be selected if **startTime** and **duration** are set.    * &#x60;PLAIN&#x60; - Values are returned as plain arrays.    * &#x60;ENCODED&#x60; - Values are returned as encoded arrays.
    /// </summary>
    /// <value>Defines the format for the distances, travel times, toll costs, directDistance flags and violation flags in the response. Note that the encoded format should be selected if **startTime** and **duration** are set.    * &#x60;PLAIN&#x60; - Values are returned as plain arrays.    * &#x60;ENCODED&#x60; - Values are returned as encoded arrays.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ResultFormat
    {
        /// <summary>
        /// Enum PLAIN for value: PLAIN
        /// </summary>
        [EnumMember(Value = "PLAIN")]
        PLAIN = 1,

        /// <summary>
        /// Enum ENCODED for value: ENCODED
        /// </summary>
        [EnumMember(Value = "ENCODED")]
        ENCODED = 2
    }

}
