/*
 * Matrix Routing
 *
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.9
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = PTV.Developer.Clients.matrixrouting.Client.OpenAPIDateConverter;

namespace PTV.Developer.Clients.matrixrouting.Model
{
    /// <summary>
    /// Defines how to consider traffic in a matrix calculation. * &#x60;AVERAGE&#x60; - Use the average **travelTime** for the selected vehicle.  If **startTime** is specified, the typical traffic situation for that time of day and day of week will be considered such as the rushhour  on Monday morning or light traffic on Saturday evening. Toll will be calculated according to that date and time. * &#x60;REALISTIC&#x60; - Use the most realistic **travelTime** for the selected vehicle and the  given **startTime**.  Takes into account the live traffic situation such as traffic jams or road works  as well as the typical traffic situation at the time of day and the day of week of travel such as the rushhour  on Monday morning or light traffic on Saturday evening.  See [here](./concepts/time-dependent-matrix) for more information. **Only available for startMatrixCalculation operation.**
    /// </summary>
    /// <value>Defines how to consider traffic in a matrix calculation. * &#x60;AVERAGE&#x60; - Use the average **travelTime** for the selected vehicle.  If **startTime** is specified, the typical traffic situation for that time of day and day of week will be considered such as the rushhour  on Monday morning or light traffic on Saturday evening. Toll will be calculated according to that date and time. * &#x60;REALISTIC&#x60; - Use the most realistic **travelTime** for the selected vehicle and the  given **startTime**.  Takes into account the live traffic situation such as traffic jams or road works  as well as the typical traffic situation at the time of day and the day of week of travel such as the rushhour  on Monday morning or light traffic on Saturday evening.  See [here](./concepts/time-dependent-matrix) for more information. **Only available for startMatrixCalculation operation.**</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TrafficMode
    {
        /// <summary>
        /// Enum AVERAGE for value: AVERAGE
        /// </summary>
        [EnumMember(Value = "AVERAGE")]
        AVERAGE = 1,

        /// <summary>
        /// Enum REALISTIC for value: REALISTIC
        /// </summary>
        [EnumMember(Value = "REALISTIC")]
        REALISTIC = 2
    }

}
