/* tslint:disable */
/* eslint-disable */
/**
 * Matrix Routing
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Defines the format for the distances, travel times, toll costs, directDistance flags and violation flags in the response.
 * Note that the encoded format should be selected if **startTime** and **duration** are set.  
 *  * `PLAIN` - Values are returned as plain arrays.  
 *  * `ENCODED` - Values are returned as encoded arrays.
 * @export
 */
export const ResultFormat = {
    PLAIN: 'PLAIN',
    ENCODED: 'ENCODED'
} as const;
export type ResultFormat = typeof ResultFormat[keyof typeof ResultFormat];


export function instanceOfResultFormat(value: any): boolean {
    for (const key in ResultFormat) {
        if (Object.prototype.hasOwnProperty.call(ResultFormat, key)) {
            if (ResultFormat[key as keyof typeof ResultFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ResultFormatFromJSON(json: any): ResultFormat {
    return ResultFormatFromJSONTyped(json, false);
}

export function ResultFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultFormat {
    return json as ResultFormat;
}

export function ResultFormatToJSON(value?: ResultFormat | null): any {
    return value as any;
}

