/* tslint:disable */
/* eslint-disable */
/**
 * Matrix Routing
 * With the Matrix Routing service you can compute distances and travel times between a set of origins and destinations.
 *
 * The version of the OpenAPI document: 1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RouteIdentifier
 */
export interface RouteIdentifier {
    /**
     * The ID of the route.
     * @type {string}
     * @memberof RouteIdentifier
     */
    routeId: string;
}

/**
 * Check if a given object implements the RouteIdentifier interface.
 */
export function instanceOfRouteIdentifier(value: object): value is RouteIdentifier {
    if (!('routeId' in value) || value['routeId'] === undefined) return false;
    return true;
}

export function RouteIdentifierFromJSON(json: any): RouteIdentifier {
    return RouteIdentifierFromJSONTyped(json, false);
}

export function RouteIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): RouteIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'routeId': json['routeId'],
    };
}

export function RouteIdentifierToJSON(value?: RouteIdentifier | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'routeId': value['routeId'],
    };
}

